### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by tobiasli** [mieubrisse/wunderpy2#1]
``` javascript
>>> pip install wunderlist2
```

``` python
>>> import wunderpy2
Traceback (most recent call last):
  File "<string>", line 301, in runcode
  File "<interactive input>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\wunderpy2\__init__.py", line 1, in <module>
    from wunderclient import WunderClient
ImportError: No module named 'wunderclient'
```

Is there an issue with the relative imports? Should it be

``` python
from .wunderclient import WunderClient
```

Or have I misunderstood something?

I have really been looking forward to wunderpy2 :) Great stuff.

**Comment by mieubrisse** [comment]
Hm, `import wunderpy2` should work out of the box. Would you mind checking a few things for me:
1. What version of Python are you running?
2. Was the installed package `wunderpy2` or `wunderlist2` ? I didn't see a wunderlist2 package on PyPI, but wasn't sure if you have a local module that's perhaps shadowing wunderpy2?
3. It looks like you're on Windows... for my repro, are you using Cygwin?

Thanks for the help!

**Comment by tobiasli** [comment]
1. I'm on Python 3.4
2. wunderpy2 (typo in description)
3. I'm on Windows, no virtualization. 

If I switched the import in `wunderpy2/__init__.py` to relative, the imports worked fine:

``` python
from .wunderclient import WunderClient
from .wunderapi import WunderApi
from .model import Task, List
```

(but the sys.path-based imports in the rest of the module will not find what they are looking for, and will also need to be relative).

I'm not well versed in these matters, but <a href="https://www.python.org/dev/peps/pep-0328">PEP0328</a> seems to state that best practice is to use dot-imports within modules like this. It would at least solve my issue :)

I can send you a pull request some day, if it's ok with you (might take some days though, because reasons).

Glad to help!

**Comment by afuerstenau** [comment]
Same problem here. Python 3.5.1, wunderpy2, Mac OS

Can you give me a hint which imports to modify?

@tobiasli Did you already send the PR?

**Comment by mieubrisse** [comment]
Hey, sorry for the low comms. I have some free time in the coming days, so
I'll check this out.

**Comment by mieubrisse** [comment]
Hey @tobiasli @afuerstenau this should be fixed now. Sorry it took so long, and let me know if you have further problems!

**Comment by gizmo410** [comment]
Hi,

Same problem here.
I'm using python 3.6.0 on Mac OS

> import wunderlistconfig
ModuleNotFoundError: No module named 'wunderlistconfig'

**Comment by mieubrisse** [comment]
Hi @gizmo410,

Is the `wunderlistconfig` module a custom module you wrote? Wunderpy doesn't have any `wunderlistconfig` module. If you're looking to import the main code module, you'll need to follow [the steps here](https://github.com/mieubrisse/wunderpy2#getting-a-client).

Cheers,
mieubrisse

**Comment by gizmo410** [comment]
Hi @mieubrisse,

Thanks for your answer. wunderlistconfig is indeed an internal module and is totally available so that shouldn't be the issue.

Cheers!

**Comment by mieubrisse** [comment]
Hey @gizmo410,

Sorry, not sure what the issue might be then if it's your custom code. The error you're getting suggests that the module isn't available; maybe you're in the wrong directory when you're trying to import it? or perhaps it's in a different directory from the script you're calling that import statement from, and isn't on the PYTHONPATH (more info on how Python's module-importing system works [here](https://docs.python.org/3/tutorial/modules.html) with [some gotchas here](http://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time))?

Cheers,
mieubrisse
