### ISSUE TITLE
Rolling a new release

### ISSUE THREAD

**Issue by d0ugal** [mieubrisse/wunderpy2#10]
Hey,

This look great. I see there are a number of fixes that have been merged into develop but are unreleased, this are particularly important for Python 3 support. I am looking at this: https://github.com/mieubrisse/wunderpy2/compare/0.1.4...develop

Is there anything I can do to help roll a new release? I want to try wunderpy2 out and if it goes well with the `develop` version I will end up pushing a fork to PyPI so I can use it (named something obscure like wunderpy2-python3-fixes). However, I'd prefer to help with the canonical version if possible.

**Comment by mieubrisse** [comment]
Hey Dougal, thanks for the reminder. I implemented the Python3 compat to fix https://github.com/mieubrisse/wunderpy2/issues/3 and tested it locally, but was hesitant to push it out without wider verification (and eventually forgot about it). Can you let me know if develop works for you? If so, I'll cut a new release and push up to PyPI (and if not, I'll fix whatever's broken).

**Comment by d0ugal** [comment]
Sure thing - thanks for getting back to me. I'll try my best to give it a go tomorrow or Friday.

**Comment by d0ugal** [comment]
I hit an issue in #11, but otherwise everything seems to work. My usage is fairly light, so I don't cover all the features.

If you are interested, I am working on integration with Home Assistant. https://github.com/home-assistant/home-assistant/

**Comment by d0ugal** [comment]
I released my patches version here, so it is easy for me and anyone else to consume. https://pypi.org/project/wunderpy2-python-3-fixes/

I called it that, but really they are Python 2 fixes also. I believe the current released version is broken for everyone. See #11.

**Comment by mieubrisse** [comment]
Hey @d0ugal , sorry for the low responsiveness. I've cut a new release, v0.1.6, today that should fix the Python 3 support using the changes that were on develop.

**Comment by d0ugal** [comment]
Thank you - I’ll check it out!
