### ISSUE TITLE
.iteritems() doesn't exist on 3.x

### ISSUE THREAD

**Issue by dwf** [mieubrisse/wunderpy2#3]
Right now various things fail because `dict.iteritems()` is gone in Python 3. I'd recommend either adding [six](https://pythonhosted.org/six/) as a dependency for things like this, or simply bundling it (it's a single file).

I can submit a PR if you tell me which you prefer (or alternately we can just add a file containing only an `iteritems` function that works on both...).

**Comment by mieubrisse** [comment]
Hey dwf,

Good catch! Adding six as a dependency sounds like a great option; a PR with that would be great.

Thanks!
mieubrisse

**Comment by eherrera1971** [comment]
I have this issue with Python 3.x
Any advice?

**Comment by mieubrisse** [comment]
Hey @eherrera1971 @dwf this should now be fixed with v0.1.6, released today (sorry for the long delay!)
