### ISSUE TITLE
Client ID Syntax error

### ISSUE THREAD

**Issue by PieterJanSterk** [mieubrisse/wunderpy2#4]
When I try to enter my credentials into the script, it keeps giving me a Syntax Error on my client ID. Here is my code.

```
import wunderpy2

access_token = MYCACCESSTOKEN
client_id = **MYCLIENTID**              <----------------------- SYNTAX ERROR

api = wunderpy2.WunderApi()
client = api.get_client(access_token, **client_id**)    <--------  OR HERE, WITH VALUE BETWEEN BRACKETS

lists = client.get_lists()
print(lists)
```

I have tried putting these values in between the api.get_client() brackets, I have tried converting them to strings. Correct me if I am wrong, but my client ID should be a 20-character alphanumeric string, right?

**Comment by mieubrisse** [comment]
Hi Pieter,

Thanks for using wunderpy! The client ID should indeed be a 20-character alphanumeric string pulled from https://developer.wunderlist.com/apps. It's strange that you're getting a syntax error even on trying to assign the value to a variable, as that's independent of the Wunderpy code. It should look something like this:

```
client = api.get_client("ifhpo076kvax77vspb6fy63i0hk9tvqh6epued887oq21fl4lepnd5ynj784", "v9kq52ivn71nppjvlk05")
```

What's the full error you're seeing?

Cheers,
mieubrisse

**Comment by PieterJanSterk** [comment]
I see what I did wrong, I did not put the key in between quotation marks. I am so, so sorry to bother you with this, it's a rookie mistake. Thank you for your time and awesome code.

**Comment by mieubrisse** [comment]
No worries; glad it worked out!
