### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by sandrobusonera** [mieubrisse/wunderpy2#5]
Hi, 

Sorry it's not really an issue but more asking you a question.

I've forked this repo and have add the "folders" endpoint but I'm not sure how to config the "**endpoint_tests**" in the tests_config.yaml in order to run the tests. Could you guide me please?

Thanks,
Sandro

**Comment by mieubrisse** [comment]
Hi @sandrobusonera, 

Tests are in a bit of an unpolished state right now, but the gist of it is: create yourself a test Wunderlist account, create an API token for this test Wunderlist account using the same method described in the README, copy `tests_config.yaml.template` to `tests_config.yaml` inside the `tests` directory, and fill in the client_id, client_secret, and access_token. Then, do `export PYTHONPATH=${PYTHONPATH}:$WUNDERPY_HOME` to add it to your PYTHONPATH and you should then be able to run any given test suite with `python -m <module>` (e.g. `python -m lists_endpoint_tests`).

Hope that helps!
mieubrisse

**Comment by sandrobusonera** [comment]
Hi @mieubrisse,

Thanks for your help, **folders** tests pass and I've sent you a pull request.

Thanks,
Sandro
